ALTER TABLE users
    ADD COLUMN IF NOT EXISTS first_name VARCHAR(255);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS last_name VARCHAR(255);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS phone VARCHAR(50);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS profile_image_url VARCHAR(500);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS email_verified BOOLEAN DEFAULT FALSE;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;