server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/servicehub_booking
    username: postgres
    password: Divya@88

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka