server:
  port: 8080

spring:
  application:
    name: gateway-service         # స్ప్రింగ్ అప్లికేషన్ నేమ్

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false          # కస్టమ్ రౌట్స్ కోసం దీనిని false చేయాలి
          lower-case-service-id: true

      server:
        webflux:
          routes:
            - id: auth-service-route
              uri: lb://AUTH-SERVICE  # Eureka లో రిజిస్టర్ అయిన EXACT పేరు
              predicates:
                - Path=/api/auth/**   # URL Mismatch కాకుండా గేట్‌వే దీనిని సజావుగా ఫార్వర్డ్ చేస్తుంది

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    com.netflix.eureka: DEBUG